// packages/dashboard/components/AppSignUpForm.vue
<template>
    <div class="w-full max-w-xs">
        <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" @submit.prevent="signup">
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="first_name">
                    First Name
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    name="first_name" type="text" placeholder="First Name">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="last_name">
                    Last Name
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    name="last_name" type="text" placeholder="Last Name">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                    Email
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    name="email" type="email" placeholder="Last Name">
            </div>
            <div class="mb-6">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                    Password
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                    name="password" type="password" placeholder="******************">
            </div>
            <div class="flex items-center justify-between">
                <button
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full text-center"
                    type="submit">
                    Create Account
                </button>
            </div>
        </form>

        <NuxtLink
            class="inline-block w-full align-baseline font-bold text-sm text-blue-500 hover:text-blue-800 text-center mb-4"
            to="/login">
            Sign in
        </NuxtLink>

        <p class="text-center text-gray-500 text-xs">
            &copy;2020 Acme Corp. All rights reserved.
        </p>
    </div>
</template>

<script setup lang="ts">
import { useUserStore } from "../store/user"

async function signup(event: Event) {
    const form = event.target as HTMLFormElement
    const formData = new FormData(form)
    const submissionObject = {}

    formData.entries().forEach(([key, value]) => {
        submissionObject[key] = value
    })

    const res = await $fetch('/api/signup', {
        method: "POST",
        body: submissionObject
    })


    document.cookie = `friendly_sites_token=${res.token}`

    const { refreshUser, user } = useUserStore()

    refreshUser().then(() => console.log(user.value))
}
</script>

// packages/frontend/src/components/AppSignUpForm.tsx
import { useState, type FormEventHandler } from 'react'
import { client } from '../utils/useApi'
import FormInput from './FormInput'
import { useUserStore } from '../stores/user'
import { useNavigate } from 'react-router-dom'

export default function AppSignUpForm() {

    const [isBusy, setIsBusy] = useState(false)
    const setToken = useUserStore((state) => state.setToken)
    const navigate = useNavigate()

    const formHandler: FormEventHandler<HTMLFormElement> = async (event) => {

        event.preventDefault()

        setIsBusy(true)

        const form = event.target as HTMLFormElement
        const details = new FormData(form).entries().reduce((accumulator: Record<string, any>, current: [string, any]) => {
            accumulator[current[0]] = current[1]
            return accumulator
        }, {})

        try {
            const res = await client.api.signup.$post({
                json: details
            })
            const { token } = await res.json()
            setToken(token)
        } catch (e) {
            console.log(e)
        } finally {
            setIsBusy(false)
        }
    }

    function signInButtonHandler() {
        navigate('/login')
    }

    return (
        <>
            <form onSubmit={formHandler}>
                <div className=" mb-3 items-center flex justify-center text-white h-24 rounded-md bg-slate-800">
                    <h3 className="text-2xl">
                        Sign Up
                    </h3>
                </div>
                <div className='mb-3'>
                    <div className='mb-2'>
                        <FormInput name="first_name" label="First Name" type="text" required />
                    </div>
                    <div className='mb-2'>
                        <FormInput name="last_name" label="First Name" type="text" required />
                    </div>
                    <div className='mb-2'>
                        <FormInput name="email" label="Email" type="email" required />
                    </div>
                    <FormInput name="password" label="Password" type="password" required={true} />
                </div>

                <button type='submit' disabled={isBusy} className="w-full rounded-md bg-slate-800 py-2 px-4 border border-transparent text-center text-sm text-white transition-all shadow-md hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none">
                    Sign Up
                </button>
            </form>

            <div className="p-6 pt-0">
                <p className="flex justify-center mt-6 text-sm text-slate-600">
                    <button onClick={signInButtonHandler} className="ml-1 text-sm font-semibold text-slate-700 underline">Sign In</button>
                </p>
            </div>

        </>
    )
}
